### ISSUE TITLE
RFE Questions from Rick

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#196]
Question 1.
Under buildosx/InstallOSX
why not use the generic name  "plugin_pi.pkproj.in"  and  "plugin_pi.pkgproj.in.jon"  so that we can use compare programs like MergeWin  to actually compare files? 

Also it makes for less work!

Question: What are these  .DS_Store files for? Do I need them?

Also under flatpak/org.opencpn.OpenCPN.Plugin.vdr.yml      why couldn't it be more generic?

or perhaps make an  .in file and generate the file?   Using simiilar technique to TestPlugin?

Question 2. 
Shipdriver  config..yml

xcode version should be changed

```
 build-macos:
    macos:
      xcode: "12.5.1"
    environment:
      - OCPN_TARGET: macos
    steps:
      - checkout
      - restore_cache:
          keys:

```
