### ISSUE TITLE
SD Manual - Control of builds circleci/config.yml

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#259]
Using SD Template  I am not sure how to do this with SD config.yml though
https://github.com/Rasbats/shipdriver_pi/blob/master/.circleci/config.yml

Using TP Template we can control deployment to Cloudsmith and  what builds with some ease.
See https://github.com/rgleason/watchdog_pi/tree/master/.circleci
note the use of

```
parameters:
    run_workflow_deploy:
        type: boolean
        default: true

    run_build_armhf_stretch:
        type: boolean
        default: true
    run_build_armhf_buster:
        type: boolean
        default: true
    run_build_armhf_bionic_64:
        type: boolean
        default: true
```

and  a typical job using    "when"  "condition: <<pipeline.parameters.run_workflow_deploy>>"

```
jobs:
    build-armhf-stretch:
        machine:
            image: ubuntu-2004:202104-01
        environment:
        - OCPN_TARGET=stretch-armhf
        - DOCKER_IMAGE=balenalib/raspberry-pi-debian:stretch
        - BUILD_FLAGS=-j3
        - BUILD_ENV=raspbian
        - DEPLOY_USE_ORB: true
        steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - when:
            condition: <<pipeline.parameters.run_workflow_deploy>>
            steps:
            - cloudsmith/ensure-api-key
            - cloudsmith/install-cli
            - run: ci/cloudsmith-upload.sh

```

I am sure there is a better way of doing this, but I use text editor search (true) and replace  (false)  etc.
